FROM toposoid/scala-nlp:2.12.12-0.1.0

WORKDIR /app
ARG TARGET_BRANCH

ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms2g -Xmx4g"

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/scala-common.git \
&& cd scala-common \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/scala-common-nlp-japanese.git \
&& cd scala-common-nlp-japanese \
#&& git checkout -b ${TARGET_BRANCH} origin/${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& cp /tmp/wnjpn.db /app/scala-common-nlp-japanese/src/main/resources/ \
&& cp /tmp/entity_vector.model.bin /app/scala-common-nlp-japanese/src/main/resources/
